### ISSUE TITLE
Forest Research Institute, Malaysia

### ISSUE THREAD

**Issue by ManonGros** [gbif/collection-mobilization#1220]
## Forest Research Institute, Malaysia
**GRSciColl URL**: https://www.gbif.org/grscicoll/institution/3668ee79-3104-4232-9a68-3de79664e90a
**Code**: `FRIM`
**Fuzzy name search in GBIF publisher**:
`None`

**Number of linked occurrences**: `1` (https://www.gbif.org/occurrence/search?advanced=1&institution_key=3668ee79-3104-4232-9a68-3de79664e90a)
**Publishing organizations for linked occurrences**:
* https://www.gbif.org/publisher/2f2e4f28-d929-4609-937b-9a8ebd265159

---
1. **Find out if the information is complete and up to date**:

- [x]  Check the homepage if available or google the institution name in the country. Check if all collections for that institution are represented in GRSciColl.
- [ ]  Add missing collections/information to the institution on GRSciColl directly in the registry. If some collections are digitized, put the information in the GRSciColl `Notes` field.

2. **Check if the data is also in GBIF**:

- [x]  If there are GBIF occurrence records linked, check from which dataset/publisher they come. Is the institution a registered publisher? Or do the records come from a third party publisher? Are all the collections in GRSciColl also in GBIF? (add comments to the issue)
- [ ]  If no record is linked to GRSciColl, look for the institution name on the GBIF list of publishers. Is there any corresponding publisher? Have they published any data? (add comments to the issue)
- [ ]  If data has been published on GBIF but isn’t linked to GRSciColl, notify Marie (tag ManonGros), she can link the data.
- [ ]  Translate outcome of your checks into labels. See guidelines here: https://github.com/gbif/collection-mobilization#readme

**Comment by ckotwn** [comment]
This institution entry on GRSciColl should be merged into #1254 because the only information (homepage & address) indicates that they are the same entity. However, this issue gets a linked occurrence record while the other doesn't. @ManonGros how come? Should we link the same record to #1254 after merging?

**Comment by ManonGros** [comment]
Thanks @ckotwn the data should be linked to the correct institution automatically after they are merged and the GRSciColl cache is refreshed (on Thursday) and the dataset is reinterpreted.
I will tag myself on the issue to keep an eye on it.

**Comment by ckotwn** [comment]
This institution has been merged with #1254.
