### ISSUE TITLE
Museum of Natural History, University of the Philippines

### ISSUE THREAD

**Issue by ManonGros** [gbif/collection-mobilization#1338]
## Museum of Natural History, University of the Philippines
**GRSciColl URL**: https://www.gbif.org/grscicoll/institution/befff561-bac1-48a7-9b43-251cb2d9555d
**Code**: `UPLB`
**Fuzzy name search in GBIF publisher**:
* [University of the Philippines Los Baños Museum of Natural History](https://www.gbif.org/publisher/8026aa28-6761-4550-a98a-68881c1fe55d)
* [UNIVERSITY OF SANTO TOMAS HERBARIUM](https://www.gbif.org/publisher/b0c3fb2f-1738-4f53-9ecb-9f2c27c0f0b8)

**Number of linked occurrences**: `0` (https://www.gbif.org/occurrence/search?advanced=1&institution_key=befff561-bac1-48a7-9b43-251cb2d9555d)

---
1. **Find out if the information is complete and up to date**:

- [x]  Check the homepage if available or google the institution name in the country. Check if all collections for that institution are represented in GRSciColl.
- [x]  Add missing collections/information to the institution on GRSciColl directly in the registry. If some collections are digitized, put the information in the GRSciColl `Notes` field.

2. **Check if the data is also in GBIF**:

- [x]  If there are GBIF occurrence records linked, check from which dataset/publisher they come. Is the institution a registered publisher? Or do the records come from a third party publisher? Are all the collections in GRSciColl also in GBIF? (add comments to the issue)
- [x]  If no record is linked to GRSciColl, look for the institution name on the GBIF list of publishers. Is there any corresponding publisher? Have they published any data? (add comments to the issue)
- [x]  If data has been published on GBIF but isn’t linked to GRSciColl, notify Marie (tag ManonGros), she can link the data.
- [x]  Translate outcome of your checks into labels. See guidelines here: https://github.com/gbif/collection-mobilization#readme

**Comment by lilee-sh** [comment]
- This issue is duplicate to https://github.com/gbif/collection-mobilization/issues/1346 and thus the institutions are merged in GRSciColl and the issue here closed
