### ISSUE TITLE
National Museum of Natural Science

### ISSUE THREAD

**Issue by ManonGros** [gbif/collection-mobilization#1389]
## National Museum of Natural Science
**GRSciColl URL**: https://www.gbif.org/grscicoll/institution/901dcfe2-4126-4a10-ae67-1f889daf41ed
**Code**: `NMNS`
**Fuzzy name search in GBIF publisher**: `none`

**Number of linked occurrences**: `61085` (https://www.gbif.org/occurrence/search?advanced=1&institution_key=901dcfe2-4126-4a10-ae67-1f889daf41ed)
**Publishing organizations for linked occurrences**:
* https://www.gbif.org/publisher/4fd82480-ea1c-11da-8db4-b8a03c50a862
* https://www.gbif.org/publisher/7050ce20-c75e-11dd-87ef-b8a03c50a862

---
1. **Find out if the information is complete and up to date**:

- [ ]  Check the homepage if available or google the institution name in the country. Check if all collections for that institution are represented in GRSciColl.
- [ ]  Add missing collections/information to the institution on GRSciColl directly in the registry. If some collections are digitized, put the information in the GRSciColl `Notes` field.

2. **Check if the data is also in GBIF**:

- [x]  If there are GBIF occurrence records linked, check from which dataset/publisher they come. Is the institution a registered publisher? Or do the records come from a third party publisher? Are all the collections in GRSciColl also in GBIF? (add comments to the issue)
- [x]  If no record is linked to GRSciColl, look for the institution name on the GBIF list of publishers. Is there any corresponding publisher? Have they published any data? (add comments to the issue)
- [x]  If data has been published on GBIF but isn’t linked to GRSciColl, notify Marie (tag ManonGros), she can link the data.
- [x]  Translate outcome of your checks into labels. See guidelines here: https://github.com/gbif/collection-mobilization#readme

**Comment by melissa0520** [comment]
@ManonGros these occurrences are not linked to GRSciColl yet: https://www.gbif.org/occurrence/search?dataset_key=fb93fb10-f1ca-11dd-b2d4-b8a03c50a862&taxon_key=1&advanced=1

**Comment by ManonGros** [comment]
@melissa0520 as far as I can see, they are linked to GRSciColl (at least the ones I clicked on), do you have any specific example that aren't linked to anything?

**Comment by melissa0520** [comment]
@ManonGros You are right. Sorry that I checked it on the metrics page and didn’t see it is included (now I see it)...

But now I found some of the occurrences are mis-linked such as 
- https://www.gbif.org/occurrence/4404423314
- https://www.gbif.org/occurrence/4404423307
- https://www.gbif.org/occurrence/3866015303

maybe because the institution name/ institution code is the same as the one in Japan?

**Comment by ckotwn** [comment]
After a discussion with the current collection section chief, this (almost empty) entry was merged with #1406 .
