### ISSUE TITLE
Prince of Songkla University

### ISSUE THREAD

**Issue by ManonGros** [gbif/collection-mobilization#1505]
## Prince of Songkla University
**GRSciColl URL**: https://www.gbif.org/grscicoll/institution/e498bb21-4904-40ca-a495-fa997d912394
**Synchronized with** `IH`
**Code**: `PSU`
**Fuzzy name search in GBIF publisher**:
* [Princess Maha Chakri Sirindhorn Natural History Museum  (PSU Museum, Prince of Songkla University, Thailand)](https://www.gbif.org/publisher/80c3ad34-82b5-457d-bb9b-1d6e1b84fae6)

**Number of linked occurrences**: `951` (https://www.gbif.org/occurrence/search?advanced=1&institution_key=e498bb21-4904-40ca-a495-fa997d912394)
**Publishing organizations for linked occurrences**:
* https://www.gbif.org/publisher/80c3ad34-82b5-457d-bb9b-1d6e1b84fae6

---
1. **Find out if the information is complete and up to date**:

- [x]  Check the homepage if available or google the institution name in the country. Check if all collections for that institution are represented in GRSciColl.
- [ ]  Add missing collections/information to the institution on GRSciColl directly in the registry. If some collections are digitized, put the information in the GRSciColl `Notes` field.

2. **Check if the data is also in GBIF**:

- [x]  If there are GBIF occurrence records linked, check from which dataset/publisher they come. Is the institution a registered publisher? Or do the records come from a third party publisher? Are all the collections in GRSciColl also in GBIF? (add comments to the issue)
- [ ]  If no record is linked to GRSciColl, look for the institution name on the GBIF list of publishers. Is there any corresponding publisher? Have they published any data? (add comments to the issue)
- [ ]  If data has been published on GBIF but isn’t linked to GRSciColl, notify Marie (tag ManonGros), she can link the data.
- [ ]  Translate outcome of your checks into labels. See guidelines here: https://github.com/gbif/collection-mobilization#readme

**Comment by ckotwn** [comment]
According to their [website](https://nhm.psu.ac.th/), PSU is a museum hosting both zoological and botanical collections. The linked herbarium records are published by the same publisher #1423 which also publishes zoological occurrences. Thus, this institution entry is merged with #1423 https://registry.gbif.org/institution/874ed64b-68f6-421a-a03b-5e64e67388a9, to which the IH-linked herbarium collection is re-assigned.
