### ISSUE TITLE
University of Lagos

### ISSUE THREAD

**Issue by ManonGros** [gbif/collection-mobilization#1574]
## University of Lagos
**GRSciColl URL**: https://www.gbif.org/grscicoll/institution/470d13b1-8b8e-4ec7-891d-98b595cc6e2e
**Synchronized with** `IH`
**Code**: `ULN`
**Fuzzy name search in GBIF publisher**:
* [Lagos State University](https://www.gbif.org/publisher/bfa2d225-ee70-40ba-8eae-b9e5e59ddeec)
* [University of Lagos](https://www.gbif.org/publisher/bdee9e20-df5e-4ef8-a012-53d2e83010e4)

**Number of linked occurrences**: `0` (https://www.gbif.org/occurrence/search?advanced=1&institution_key=470d13b1-8b8e-4ec7-891d-98b595cc6e2e)

---
1. **Find out if the information is complete and up to date**:

- [x]  Check the homepage if available or google the institution name in the country. Check if all collections for that institution are represented in GRSciColl.
- [x]  Add missing collections/information to the institution on GRSciColl directly in the registry. If some collections are digitized, put the information in the GRSciColl `Notes` field.

2. **Check if the data is also in GBIF**:

- [x]  If there are GBIF occurrence records linked, check from which dataset/publisher they come. Is the institution a registered publisher? Or do the records come from a third party publisher? Are all the collections in GRSciColl also in GBIF? (add comments to the issue)
- [x]  If no record is linked to GRSciColl, look for the institution name on the GBIF list of publishers. Is there any corresponding publisher? Have they published any data? (add comments to the issue)
- [x]  If data has been published on GBIF but isn’t linked to GRSciColl, notify Marie (tag ManonGros), she can link the data.
- [x]  Translate outcome of your checks into labels. See guidelines here: https://github.com/gbif/collection-mobilization#readme

**Comment by lmusinguzi** [comment]
suggested deletion

**Comment by ManonGros** [comment]
Don't delete the institution if you can merge them for another one.
In this case, I restored the institution and merged it with https://github.com/gbif/collection-mobilization/issues/1577
