### ISSUE TITLE
University of Ghana

### ISSUE THREAD

**Issue by ManonGros** [gbif/collection-mobilization#1623]
## University of Ghana
**GRSciColl URL**: https://www.gbif.org/grscicoll/institution/9acc0a1f-a84b-4f6f-9bf5-d510e1a4eb75
**Code**: `UG`
**Fuzzy name search in GBIF publisher**:
* [Department of Marine and Fisheries Sciences, University of Ghana](https://www.gbif.org/publisher/c2465426-2110-46d2-a06f-8accaedca40d)
* [Ghana Biodiversity Information Facility (GhaBIF)](https://www.gbif.org/publisher/4bc4943a-c94f-4bd4-9aa3-2a9cae94398a)
* [Department of Animal Biology and Conservation Sciences, University of Ghana](https://www.gbif.org/publisher/fb0de436-2142-4d7d-af11-4b44de68d382)

**Number of linked occurrences**: `0` (https://www.gbif.org/occurrence/search?advanced=1&institution_key=9acc0a1f-a84b-4f6f-9bf5-d510e1a4eb75)

---
1. **Find out if the information is complete and up to date**:

- [x]  Check the homepage if available or google the institution name in the country. Check if all collections for that institution are represented in GRSciColl.
- [x]  Add missing collections/information to the institution on GRSciColl directly in the registry. If some collections are digitized, put the information in the GRSciColl `Notes` field.

2. **Check if the data is also in GBIF**:

- [x]  If there are GBIF occurrence records linked, check from which dataset/publisher they come. Is the institution a registered publisher? Or do the records come from a third party publisher? Are all the collections in GRSciColl also in GBIF? (add comments to the issue)
- [x]  If no record is linked to GRSciColl, look for the institution name on the GBIF list of publishers. Is there any corresponding publisher? Have they published any data? (add comments to the issue)
- [x]  If data has been published on GBIF but isn’t linked to GRSciColl, notify Marie (tag ManonGros), she can link the data.
- [x]  Translate outcome of your checks into labels. See guidelines here: https://github.com/gbif/collection-mobilization#readme

**Comment by lmusinguzi** [comment]
Institution recommended for deleting. It has no collection and is similar to institution #1627

**Comment by ManonGros** [comment]
The entry has been merged with: https://www.gbif.org/grscicoll/institution/53d707bc-8acb-42cf-af28-82416b20baa8
