### ISSUE TITLE
Haramaya University

### ISSUE THREAD

**Issue by ManonGros** [gbif/collection-mobilization#1741]
## Haramaya University
**GRSciColl URL**: https://www.gbif.org/grscicoll/institution/609dede8-6985-42aa-a23f-8676f03ea20b
**Synchronized with** `IH`
**Code**: `HUHE`
**Homepage**: http://www.haramaya.edu.et
**Fuzzy name search in GBIF publisher**:
`None`

**Number of linked occurrences**: `0` (https://www.gbif.org/occurrence/search?advanced=1&institution_key=609dede8-6985-42aa-a23f-8676f03ea20b)

---
1. **Find out if the information is complete and up to date**:

- [x]  Check the homepage if available or google the institution name in the country. Check if all collections for that institution are represented in GRSciColl.
- [x]  Add missing collections/information to the institution on GRSciColl directly in the registry. If some collections are digitized, put the information in the GRSciColl `Notes` field.

2. **Check if the data is also in GBIF**:

- [x]  If there are GBIF occurrence records linked, check from which dataset/publisher they come. Is the institution a registered publisher? Or do the records come from a third party publisher? Are all the collections in GRSciColl also in GBIF? (add comments to the issue)
- [x]  If no record is linked to GRSciColl, look for the institution name on the GBIF list of publishers. Is there any corresponding publisher? Have they published any data? (add comments to the issue)
- [x]  If data has been published on GBIF but isn’t linked to GRSciColl, notify Marie (tag ManonGros), she can link the data.
- [x]  Translate outcome of your checks into labels. See guidelines here: https://github.com/gbif/collection-mobilization#readme

**Comment by lmusinguzi** [comment]
@ManonGros Please accept the proposed name of change of #1744 to [Haramaya University](https://registry.gbif.org/institution/609dede8-6985-42aa-a23f-8676f03ea20b). After that, this institution #1741 should be deleted together with its collection https://registry.gbif.org/collection/0d37530d-d534-49ab-a954-3cbbe9998f9c. This is to intended to remove duplicates. The collection that will remain (https://registry.gbif.org/institution/6b357636-fb40-417e-a3af-9ad1fbec2b9d) is the collection carrying the legacy code ACD which is featured in versions of Index Herbariorum.

**Comment by ManonGros** [comment]
Thanks @lmusinguzi I merged the institution entries but I cannot delete a collection that exists in Index Herbarium. For now HUHE will have to remain as a collection.
