### ISSUE TITLE
Herbarium - Sofia University

### ISSUE THREAD

**Issue by ManonGros** [gbif/collection-mobilization#2004]
## Herbarium - Sofia University
**GRSciColl URL**: https://www.gbif.org/grscicoll/institution/ce076168-d81d-4157-b95d-9c37ba734f34
**Synchronized with** `IH`
**Code**: `SO`
**Homepage**: https://www.uni-sofia.bg/index.php/bul/universitet_t/fakulteti/biologicheski_fakultet2/herbarium_so
**Fuzzy name search in GBIF publisher**:
`None`

**Number of linked occurrences**: `5` (https://www.gbif.org/occurrence/search?advanced=1&institution_key=ce076168-d81d-4157-b95d-9c37ba734f34)
**Publishing organizations for linked occurrences**:
* https://www.gbif.org/publisher/90fd6680-349f-11d8-aa2d-b8a03c50a862

---
1. **Find out if the information is complete and up to date**:

- [x]  Check the homepage if available or google the institution name in the country. Check if all collections for that institution are represented in GRSciColl.
- [x]  Add missing collections/information to the institution on GRSciColl directly in the registry. If some collections are digitized, put the information in the GRSciColl `Notes` field.

2. **Check if the data is also in GBIF**:

- [x]  If there are GBIF occurrence records linked, check from which dataset/publisher they come. Is the institution a registered publisher? Or do the records come from a third party publisher? Are all the collections in GRSciColl also in GBIF? (add comments to the issue)
- [x]  If no record is linked to GRSciColl, look for the institution name on the GBIF list of publishers. Is there any corresponding publisher? Have they published any data? (add comments to the issue)
- [x]  If data has been published on GBIF but isn’t linked to GRSciColl, notify Marie (tag ManonGros), she can link the data.
- [x]  Translate outcome of your checks into labels. See guidelines here: https://github.com/gbif/collection-mobilization#readme

**Comment by spalp** [comment]
I broke the connection with the Master Source (Indeh Herbariorum) and merged with another institution:[ Sofia university, Faculty of Biology](https://www.gbif.org/grscicoll/institution/70b18cea-8fba-41ac-94e2-f04b9640a2a5)

**Comment by spalp** [comment]
> @spalp I restored the institution. Could you check everything seems correct?

Yes, I see both the issue and at the GRSciColl website. Thanks.

**Comment by spalp** [comment]
3 occurrences are coming from specimens from the herbarium SO:      [SO-101206 | SO-105775 | SO105807](https://www.gbif.org/occurrence/charts?catalog_number=SO-101206&catalog_number=SO-105775&catalog_number=SO105807&advanced=1), the first 2 are part of the [INSDC sequences](https://www.gbif.org/dataset/d8cd16ba-bb74-4420-821e-083f2bac17c2) dataset, the third is from [iBOL](https://www.gbif.org/dataset/040c5662-da76-4782-a48e-cdea1892d14c)

**Comment by spalp** [comment]
- [ ] Check GBIF  for specimen data with **Collection code = SO**: https://www.gbif.org/occurrence/search?offset=0&basis_of_record=MATERIAL_SAMPLE&basis_of_record=PRESERVED_SPECIMEN&basis_of_record=MATERIAL_CITATION&institution_code=SO **6 occurrences** - only 1 from Herbarium SO (**2023-11-06**), see previous comment

- [ ] Check GBIF  for specimen data with **Collection code = SO**: https://www.gbif.org/occurrence/search?basis_of_record=MATERIAL_SAMPLE&basis_of_record=PRESERVED_SPECIMEN&basis_of_record=MATERIAL_CITATION&collection_code=SO : **32 occurrences** - none seem to be from Herbarium SO (**2023-11-06**)

**Comment by spalp** [comment]
Collections moved under https://registry.gbif.org/institution/70b18cea-8fba-41ac-94e2-f04b9640a2a5, with which the institution was merged
