### ISSUE TITLE
Faculty of Science, The University of Novi Sad

### ISSUE THREAD

**Issue by ManonGros** [gbif/collection-mobilization#2102]
## Faculty of Science, The University of Novi Sad
**GRSciColl URL**: https://www.gbif.org/grscicoll/institution/233f52b3-56b0-4f0d-9c1b-ef4459332f44
**Code**: `FSUNS`
**Fuzzy name search in GBIF publisher**:
* [Department of Biology and Ecology, Faculty of Sciences, University of Novi Sad, Serbia](https://www.gbif.org/publisher/088741fa-d695-4cec-ae3b-9c6dc4539ca1)

**Number of linked occurrences**: `0` (https://www.gbif.org/occurrence/search?advanced=1&institution_key=233f52b3-56b0-4f0d-9c1b-ef4459332f44)

---
1. **Find out if the information is complete and up to date**:

- [x]  Check the homepage if available or google the institution name in the country. Check if all collections for that institution are represented in GRSciColl.
- [x]  Add missing collections/information to the institution on GRSciColl directly in the registry. If some collections are digitized, put the information in the GRSciColl `Notes` field.

2. **Check if the data is also in GBIF**:

- [x]  If there are GBIF occurrence records linked, check from which dataset/publisher they come. Is the institution a registered publisher? Or do the records come from a third party publisher? Are all the collections in GRSciColl also in GBIF? (add comments to the issue)
- [x]  If no record is linked to GRSciColl, look for the institution name on the GBIF list of publishers. Is there any corresponding publisher? Have they published any data? (add comments to the issue)
- [x]  If data has been published on GBIF but isn’t linked to GRSciColl, notify Marie (tag ManonGros), she can link the data.
- [x]  Translate outcome of your checks into labels. See guidelines here: https://github.com/gbif/collection-mobilization#readme

**Comment by spalp** [comment]
This institution is a duplicate and was replaced by [Department of Biology and Ecology, University of Novi Sad](https://registry.gbif.org/institution/e208c3eb-21b7-42cd-9ff0-0dafea1d23d1).
